# SPDX-License-Identifier: ISC
---
name: lint

on:
  pull_request:
    paths:
      - .github/workflows/lint.yml
      - packer/
  push:
    paths:
      - .github/workflows/lint.yml
      - packer/
  workflow_dispatch:

jobs:
  packer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: packer init
        run: packer init ./packer

      - name: packer validate
        run: packer validate -syntax-only ./packer
